name: Build & Push Docker image

on:
  push:
    branches: [main]
  release:
    types: [published]
  # vagy tag push alapján:
  # push:
  #   tags:
  #     - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker tags
        id: vars
        run: |
          VERSION="latest"
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION="${{ github.event.release.tag_name }}"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            0x6572696b/staking-deposit-cli:latest
            0x6572696b/staking-deposit-cli:${{ steps.vars.outputs.version_tag }}